# for local services like message generation
# first
# docker-compose run --rm php composer update
# second
# docker-compose run --rm php ./yii message ./messageConfig.php
version: '3'
services:
  php:
    image: bscheshir/php:7.3.5-fpm-alpine-4yii2-xdebug
    restart: always
    volumes:
      - .:/var/www/html
      - ~/.composer/cache:/root/.composer/cache
    environment:
      TZ: Europe/Moscow
  node:
    image: node:8.16.0-alpine
    volumes:
      - .:/var/www/html
